/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xml.reader;
import java.io.InputStream;
import java.io.File;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ReadXMLFile reader = new ReadXMLFile();
        reader.run();
  }

}
